name: Setup Windows RDP via Tailscale

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install dan Connect Tailscale
        run: |
          Write-Host "Mengunduh Tailscale..."
          Invoke-WebRequest -Uri 'https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe' -OutFile 'tailscale-setup.exe'
          
          Write-Host "Menginstal Tailscale secara diam-diam (silent)..."
          Start-Process -FilePath '.\tailscale-setup.exe' -ArgumentList '/quiet' -Wait
          
          Write-Host "Menjalankan dan autentikasi Tailscale..."
          # Pastikan path instalasi sesuai dengan default Windows
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --unattended
          
          Write-Host "Tailscale IP:"
          & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        shell: powershell

      - name: Membuat User dan Mengaktifkan RDP
        run: |
          Write-Host "Menambahkan User..."
          net user Adysetia Ady@123 /add
          net localgroup administrators Adysetia /add
          
          Write-Host "Mengaktifkan RDP..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        shell: powershell

      - name: Menjaga RDP Tetap Aktif
        run: |
          Write-Host "========================================"
          Write-Host "RDP Server is running. You can connect now."
          Write-Host "Username: Adysetia"
          Write-Host "Password: Ady@123"
          Write-Host "Silakan cek log 'Install dan Connect Tailscale' di atas untuk melihat IP Tailscale Anda."
          Write-Host "========================================"
          # Menahan agar workflow tidak langsung selesai
          Start-Sleep -Seconds 21600
        shell: powershell
