name: Setup Windows RDP via Pinggy

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Membuat User dan Mengaktifkan RDP
        run: |
          net user Adysetia Ady@123 /add
          net localgroup administrators Adysetia /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        shell: powershell

      - name: Menjalankan Pinggy Tunnel
        shell: bash
        run: |
          echo "Membuka jalur tunnel menggunakan Pinggy..."
          
          # Menjalankan SSH di background menggunakan Bash agar output terbaca
          ssh -p 443 -R0:localhost:3389 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 tcp@a.pinggy.io > pinggy.log 2>&1 &
          
          # Tunggu 15 detik agar server Pinggy memberikan URL-nya
          sleep 15
          
          echo "========================================"
          echo "LOG KONEKSI:"
          cat pinggy.log
          echo "========================================"
          echo "Cari baris yang berawalan tcp:// (Misal: tcp://xxxx.a.free.pinggy.link:12345)"

      - name: Menjaga RDP Tetap Aktif
        run: |
          Write-Host "Username: Adysetia"
          Write-Host "Password: Ady@123"
          Start-Sleep -Seconds 21600
        shell: powershell
        
